### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [openvita/openvita-pwa#3]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/openvita/openvita-pwa/blob/master/package.json#L54

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs` and `yarn remove fs`.

**Comment by openvita** [comment]
Thank for the tip. Should be fixed now.
